name = "sentinel"
main = "sentinel.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# [triggers]
# crons = ["*/10 * * * *"]  # Every 10 minutes - PAUSED

# [[kv_namespaces]]
# binding = "SENTINEL_KV"
# id = "5898869a24434a1985267998fa95b596"
