name: Sentinel Changelog Monitor

on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
  workflow_dispatch: # Allow manual runs

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create cache directory
        run: mkdir -p cache

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: cache/
          key: sentinel-cache-${{ github.run_id }}
          restore-keys: |
            sentinel-cache-

      - name: Run sentinel
        run: bun run index.ts
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Save cache
        uses: actions/cache@v4
        with:
          path: cache/
          key: sentinel-cache-${{ github.run_id }}
